### PR TITLE
Added Key Advances column Gen5 DreamRadar

### PR DESCRIPTION
**Pull request by Real96**
Advances in DreamRadar rng now matches perfectly in game advances. Tested many times and now perfectly working, also the researcher.

### CODE REVIEW

**Comment by Admiral-Fish** [comment]
Why is this necessary?

**Comment by Real96** [comment]
> Why is this necessary?

To match game advances. It would be better imo, first time i tested it i didn't understood what i was doing wrong. I think this would be less confusing. All the other rng just follow game advances, this is the only different one.

**Comment by Real96** [comment]
In these screen there are original pokefinder at the left, my pr pokefinder and the in game advances showed by DeSmuMe. As you can see initial advances aren't 0. My pr match perfectly the game,

**Comment by Real96** [comment]
Modified as agreed on discord. Both Generator and Searcher are fully working!
image

**Comment by Admiral-Fish** [comment]
Can you fix merge conflicts and then make DreamRadarState header only? Then I can merge.

**Comment by Real96** [comment]
> Can you fix merge conflicts and then make DreamRadarState header only? Then I can merge.

Fixed merge conflicts and made DreamRadarState header only. Pls merge before new merge conflicts appear t.t

**Pull request merged**
